const chains = [
  //=========================={                       }==============================
  //=========================={    NATIVE Tokens      }==============================
  //=========================={                       }==============================

  {
    chainId: 1,
    name: 'Ethereum',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'ETH',
    logoUrl: 'https://govercity.com/assets/images/logos/eth.svg', // of token
    networkName: 'homestead',
    currency: 'ETH',
    decimals: 18,
    explorerName: 'Etherscan',
    explorerUrl: 'https://etherscan.io',
    explorerApi: 'https://api.etherscan.io/api',
    networkRpc: 'https://cloudflare-eth.com',
    networkRpc2: 'https://rpc.ankr.com/multichain',
    icon: 'https://govercity.com/assets/images/logos/eth..svg',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'ETH',
  },
  {
    chainId: 137,
    name: 'Polygon', // of token
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'MATIC',
    logoUrl: 'https://govercity.com/assets/images/logos/matic.svg', // of token
    networkName: 'matic',
    currency: 'MATIC',
    decimals: 18,
    explorerName: 'PolygonScan',
    explorerUrl: 'https://polygonscan.com',
    explorerApi: 'https://api.polygonscan.com/api',
    networkRpc: 'https://polygon-rpc.com',
    networkRpc2: 'https://rpc.ankr.com/multichain',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'POLYGON',
  },
  {
    chainId: 10,
    name: 'Optimism', // of token
    //address: '0x4200000000000000000000000000000000000042', // of token
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'op',
    logoUrl: 'https://govercity.com/assets/images/logos/op.svg', // of token
    networkName: 'optimism',
    currency: 'ETH',
    decimals: 18,
    explorerName: 'Etherscan',
    explorerUrl: 'https://optimistic.etherscan.io',
    explorerApi: 'https://api-optimistic.etherscan.io/api',
    networkRpc: 'https://mainnet.optimism.io',
    networkRpc2: 'https://rpc.ankr.com/multichain',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'OP',
  },
  // No logo
  {
    chainId: 42161,
    name: 'Arbitrum One', // of token
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'ARBITRUM',
    logoUrl: 'https://govercity.com/assets/images/logos/', // of token
    networkName: 'arbitrum',
    currency: 'ETH',
    decimals: 18,
    explorerName: 'Arbiscan',
    explorerUrl: 'https://arbiscan.io',
    explorerApi: 'https://api.arbiscan.io/api',
    networkRpc: 'https://arb1.arbitrum.io/rpc',
    networkRpc2: 'https://rpc.ankr.com/multichain',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'ARBITRUM',
  },
  {
    chainId: 56,
    name: 'Binance Smart Chain',
    symbol: 'BNB',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    logoUrl: 'https://govercity.com/assets/images/logos/bnb.svg', // of token
    networkName: 'Binance Smart Chain',
    currency: 'BNB',
    decimals: 18,
    explorerName: 'Bscscan',
    explorerUrl: 'https://bscscan.com/',
    explorerApi: '',
    networkRpc: 'https://rpc.ankr.com/bsc',
    networkRpc2: 'https://rpc.ankr.com/multichain',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'BNB',
  },
  // {
  //   chainId: 25,
  //   name: 'Cronos', // of token
  //   address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
  //   symbol: 'CRO',
  //   logoUrl: 'https://govercity.com/assets/images/logos/cro.svg', // of token
  //   networkName: 'Cronos',
  //   currency: 'CRO',
  //   decimals: 18,
  //   explorerName: '',
  //   explorerUrl: 'https://cronos.crypto.org/explorer/',
  //   explorerApi: '',
  //   networkRpc: 'https://evm-cronos.crypto.org/',
  //   networkRpc2: 'https://node.croswap.com/rpc',
  //   type: 'NATIVE',
  //   networkDecimals: 18,
  //   chain: 'CRONOS',
  // },
  // {
  //   chainId: 20,
  //   name: 'Elastos',
  //   address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
  //   symbol: 'ELA',
  //   logoUrl: 'https://govercity.com/assets/images/logos/ela.svg', // of token
  //   networkName: 'Elastos',
  //   currency: 'ELA',
  //   decimals: 18,
  //   explorerName: '',
  //   explorerUrl: 'https://explorer.elaeth.io/',
  //   explorerApi: '',
  //   networkRpc: 'https://api.elastos.io/eth',
  //   networkRpc2: '',
  //   type: 'NATIVE',
  //   networkDecimals: 18,
  //   chain: 'ELASTOS',
  // },

  {
    chainId: 43114,
    name: 'Avalanche',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'ELA',
    logoUrl: 'https://govercity.com/assets/images/logos/avax.svg',
    networkName: 'Avalanche',
    currency: 'AVAX',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://api.avax.network/ext/bc/C/rpc',
    explorerApi: '',
    networkRpc: 'https://api.avax.network/ext/bc/C/rpc',
    networkRpc2: 'https://rpc.ankr.com/multichain',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'AVAX',
  },
  {
    chainId: 250,
    name: 'Fantom', // of token
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'FTM',
    logoUrl: 'https://govercity.com/assets/images/logos/ftm.svg', // of token
    networkName: 'Fantom', // ETHEREUM Network
    currency: 'FTM',
    decimals: 18,
    explorerName: 'ftmscan',
    explorerUrl: 'https://ftmscan.com/',
    explorerApi: '',
    networkRpc: 'https://rpc.ankr.com/fantom/',
    networkRpc2: 'https://rpc.ankr.com/multichain',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'FTM',
  },
  {
    chainId: 1666600000,
    name: 'Harmony', // of token
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'ONE',
    logoUrl: 'https://govercity.com/assets/images/logos/one.svg', // of token
    networkName: 'Harmony',
    currency: 'ONE',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://explorer.harmony.one/',
    explorerApi: '',
    networkRpc: 'https://api.harmony.one/',
    networkRpc2: 'https://harmony-mainnet.chainstacklabs.com/',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'ONE',
  },
  {
    chainId: 128,
    name: 'Huobi Eco Chain', // of token
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'HT',
    logoUrl: 'https://govercity.com/assets/images/logos/ht.svg',
    networkName: 'Huobi Eco Chain',
    currency: 'HT',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://hecoinfo.com/',
    explorerApi: '',
    networkRpc: 'https://http-mainnet-node.huobichain.com/',
    networkRpc2: '',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'HT',
  },
  {
    chainId: 321,
    name: 'KuCoin Chain',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'KCS',
    logoUrl: 'https://govercity.com/assets/images/logos/kcs.svg', // of token
    networkName: 'Kucoin Chain',
    currency: 'KCS',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://scan.kcc.network/',
    explorerApi: '',
    networkRpc: 'https://rpc-mainnet.kcc.network/',
    networkRpc2: '',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'KCS',
  },
  //No logo
  {
    chainId: 11155111,
    name: 'Sepolia',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'ETH',
    logoUrl: 'https://govercity.com/assets/images/logos/', // of token
    networkName: 'sepolia',
    currency: 'ETH',
    decimals: 18,
    explorerName: 'Etherscan',
    explorerUrl: 'https://sepolia.etherscan.io',
    explorerApi: 'https://api-sepolia.etherscan.io/api',
    networkRpc: 'https://rpc.sepolia.org',
    networkRpc2: '',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'SEPOLIA',
  },
  {
    chainId: 8,
    name: 'Ubiq',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'UBQ',
    logoUrl: 'https://govercity.com/assets/images/logos/ubiq.svg',
    networkName: 'Ubiq',
    currency: 'UBQ',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://ubiqscan.io/',
    explorerApi: '',
    networkRpc: 'https://rpc.octano.dev/',
    networkRpc2: '',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'UBIQ',
  },
  // No logo
  {
    chainId: 100,
    name: 'Gnosis',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'XDAI',
    logoUrl: 'https://govercity.com/assets/images/logos/',
    networkName: 'Gnosis',
    currency: 'XDAI',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://blockscout.com/xdai/mainnet/',
    explorerApi: '',
    networkRpc: 'https://rpc.gnosischain.com/',
    networkRpc2: 'https://rpc.ankr.com/gnosis',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'GNOSIS',
  },
  // No logo
  {
    chainId: 5551,
    name: 'Nahmii',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'ETH',
    logoUrl: 'https://govercity.com/assets/images/logos/',
    networkName: 'Nahmii',
    currency: 'ETH',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://explorer.nahmii.io/',
    explorerApi: '',
    networkRpc: 'https://l2.nahmii.io/',
    networkRpc2: '',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'NAHMII',
  },
  {
    chainId: 4689,
    name: 'IoTeX',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'IOTEX',
    logoUrl: 'https://govercity.com/assets/images/logos/iotex.svg',
    networkName: 'IoTeX',
    currency: 'IOTEX',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://iotexscan.io/',
    networkRpc: 'https://babel-api.mainnet.iotex.io/',
    networkRpc2: '',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'IOTEX',
  },
  // No logo
  {
    chainId: 42220,
    name: 'Celo',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'CELO',
    logoUrl: 'https://govercity.com/assets/images/logos/',
    networkName: 'Celo',
    currency: 'CELO',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://celoscan.com/',
    explorerApi: '',
    networkRpc: 'https://rpc.ankr.com/celo',
    networkRpc2: '',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'CELO',
  },
  // No logo
  {
    chainId: 1284,
    name: 'Moonbeam',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'GLMR',
    logoUrl: 'https://govercity.com/assets/images/logos/',
    networkName: 'Moonbeam',
    currency: 'GLMR',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://moonscan.io/',
    explorerApi: '',
    networkRpc: 'https://rpc.ankr.com/moonbeam',
    networkRpc2: '',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'MOONBEAM',
  },
  // No logo
  {
    chainId: 57,
    name: 'Syscoin mainnet',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'SYS',
    logoUrl: 'https://govercity.com/assets/images/logos/',
    networkName: 'syscoin mainnet',
    currency: 'SYS',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://explorer.syscoin.org/',
    explorerApi: '',
    networkRpc: 'https://rpc.ankr.com/syscoin',
    networkRpc2: 'https://rpc.ankr.com/multichain',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'SYSCOIN',
  },
  // No logo
  {
    chainId: 398,
    name: 'Pando',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'PTX',
    logoUrl: 'https://govercity.com/assets/images/logos/',
    networkName: 'Pando',
    currency: 'PTX',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://explorer.pandoproject.org/',
    explorerApi: '',
    networkRpc: 'https://eth-rpc-api.pandoproject.org/rpc',
    networkRpc2: '',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'PANDO',
  },
  // No logo
  {
    chainId: 70,
    name: 'Hoo',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'HOO',
    logoUrl: 'https://govercity.com/assets/images/logos/',
    networkName: 'Hoo',
    currency: 'HOO',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://hooscan.com/',
    explorerApi: '',
    networkRpc: 'https://http-mainnet.hoosmartchain.com/',
    networkRpc2: '',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'HOO',
  },
  // No logo
  {
    chainId: 1313161554,
    name: 'Aurora',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'AURORA',
    logoUrl: 'https://govercity.com/assets/images/logos/',
    networkName: 'Aurora',
    currency: 'ETH',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://aurorascan.dev/',
    explorerApi: '',
    networkRpc: 'https://mainnet.aurora.dev',
    networkRpc2: '',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'AURORA',
  }, // No logo
  {
    chainId: 11297108109,
    name: 'Palm',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'PALM',
    logoUrl: 'https://govercity.com/assets/images/logos/',
    networkName: 'Palm',
    currency: 'PALM',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://explorer.palm.io/',
    explorerApi: '',
    networkRpc:
      'https://palm-mainnet.infura.io/v3/3a961d6501e54add9a41aa53f15de99b',
    networkRpc2: '',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'PALM',
  },
  // No logo
  {
    chainId: 361,
    name: 'Theta',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'THETA',
    logoUrl: 'https://govercity.com/assets/images/logos/',
    networkName: 'Theta Network',
    currency: 'TFUEL',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://explorer.thetatoken.org/',
    explorerApi: '',
    networkRpc: 'https://eth-rpc-api.thetatoken.org/rpc',
    networkRpc2: '',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'THETA',
  },
  // No logo
  {
    chainId: 8217,
    name: 'Klaytn Cypress',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'KLAY',
    logoUrl: 'https://govercity.com/assets/images/logos/',
    networkName: 'Klaytn',
    currency: 'KLAY',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://scope.klaytn.com/',
    explorerApi: '',
    networkRpc: 'https://rpc.ankr.com/klaytn',
    networkRpc2: 'https://public-node-api.klaytnapi.com/v1/cypress',
    icon: 'https://govercity.com/assets/images/logos/',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'KLAYTN',
  },
  // No logo
  {
    chainId: 106,
    name: 'Velas',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'VLX',
    logoUrl: 'https://govercity.com/assets/images/logos/',
    networkName: 'Velas',
    currency: 'VLX',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://evmexplorer.velas.com/', // evm exploerer
    explorerApi: '',
    networkRpc: 'https://evmexplorer.velas.com/rpc',
    networkRpc2: 'https://explorer.velas.com/rpc',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'VELAS',
  },
  // No logo
  {
    chainId: 59,
    name: 'EOS',
    address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', // of token
    symbol: 'EOS',
    logoUrl: 'https://govercity.com/assets/images/logos/',
    networkName: 'EOS',
    currency: 'EOS',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://eosflare.io/',
    explorerApi: '',
    networkRpc: 'https://api.eosargentina.io',
    networkRpc2: 'https://api.metahub.cash',
    type: 'NATIVE',
    networkDecimals: 18,
    chain: 'EOS',
  },
  //=========================={                       }==============================
  //=========================={    TEST Tokens        }==============================
  //=========================={                       }==============================

  // create tokenSymbol as a new params for symbols and logoUrls for images we will be using from coinCompare for making API calls on prices
  // update the lis of tokens and add 20 new ERC20 tokens

  {
    chainId: 5,
    name: 'Goerli Ether',
    address: '', // of token
    symbol: 'GoerliETH',
    logoUrl: 'https://govercity.com/assets/images/logos/eth.svg', // of token
    networkName: 'goerli',
    currency: 'ETH',
    decimals: 18,
    explorerName: 'Etherscan',
    explorerUrl: 'https://goerli.etherscan.io',
    explorerApi: 'https://api-goerli.etherscan.io/api',
    networkRpc: 'https://rpc.ankr.com/eth_goerli',
    networkRpc2: 'https://rpc.ankr.com/gnosis',
    icon: 'https://govercity.com/assets/images/logos/eth..svg',
    type: 'TEST',
    networkDecimals: 18,
    chain: 'GOERLI',
  },
  {
    chainId: 80001,
    name: 'Polygon Mumbai',
    address: '', // of token
    symbol: 'MumbiaMATIC',
    logoUrl: 'https://govercity.com/assets/images/logos/matic.svg', // of token
    networkName: 'maticmum',
    currency: 'MATIC',
    decimals: 18,
    explorerName: 'PolygonScan',
    explorerUrl: 'https://mumbai.polygonscan.com',
    explorerApi: 'https://api-testnet.polygonscan.com/api',
    networkRpc: 'https://matic-mumbai.chainstacklabs.com',
    networkRpc2: '',
    type: 'TEST',
    networkDecimals: 18,
    chain: 'MUMBAI',
  },
  {
    chainId: 420,
    name: 'Optimism Goerli',
    address: '', // of token
    symbol: 'ETH',
    logoUrl: 'https://govercity.com/assets/images/logos/op.svg', // of token
    networkName: 'optimism-goerli',
    symbol: 'ETH',
    decimals: 18,
    explorerName: 'Etherscan',
    explorerUrl: 'https://goerli-optimism.etherscan.io',
    explorerApi: 'https://api-goerli-optimism.etherscan.io/api',
    networkRpc: 'https://goerli.optimism.io',
    networkRpc2: '',
    type: 'TEST',
    networkDecimals: 18,
    chain: 'OP',
  },
  // No Logo
  {
    chainId: 421613,
    name: 'Arbitrum Goerli Ether',
    address: '', // of token
    symbol: 'ETH',
    logoUrl: 'https://govercity.com/assets/images/logos/', // of token
    networkName: 'arbitrum-goerli',
    currency: 'ETH',
    decimals: 18,
    explorerName: 'Arbiscan',
    explorerUrl: 'https://goerli.arbiscan.io',
    explorerApi: 'https://api-goerli.arbiscan.io/api',
    networkRpc: 'https://goerli-rollup.arbitrum.io/rpc',
    networkRpc2: '',
    type: 'TEST',
    networkDecimals: 18,
    chain: 'ARBITRUM',
  },
  {
    chainId: 97,
    name: 'Smart Chain - Testnet',
    symbol: 'BNB',
    address: '',
    logoUrl: 'https://govercity.com/assets/images/logos/bnb.svg', // of token
    networkName: 'Binance Smart Chain',
    currency: 'BNB',
    decimals: 18,
    explorerName: 'Bscscan',
    explorerUrl: 'https://bscscan.com/',
    explorerApi: '',
    networkRpc: 'https://data-seed-prebsc-1-s1.binance.org:8545/',
    networkRpc2: '',
    type: 'TEST',
    networkDecimals: 18,
    chain: 'SMART CHAIN',
  },
  {
    chainId: 4002,
    name: 'Fantom',
    address: '', // of token
    symbol: 'FTM',
    logoUrl: 'https://govercity.com/assets/images/logos/ftm.svg', // of token
    networkName: 'Fantom', // ETHEREUM Network
    currency: 'FTM',
    decimals: 18,
    explorerName: 'ftmscan',
    explorerUrl: 'https://testnet.ftmscan.com/',
    explorerApi: '',
    networkRpc: 'https://rpc.testnet.fantom.network/',
    networkRpc2: 'https://rpc.ankr.com/multichain',
    type: 'TEST',
    networkDecimals: 18,
    chain: 'FTM',
  },
  {
    chainId: 100,
    name: 'Harmony',
    address: '', // of token
    symbol: 'ONE',
    logoUrl: 'https://govercity.com/assets/images/logos/one.svg', // of token
    networkName: 'Harmony',
    currency: 'ONE',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://explorer.harmony.one/',
    explorerApi: '',
    networkRpc: 'https://api.s0.b.hmny.io/',
    networkRpc2: '',
    type: 'TEST',
    networkDecimals: 18,
    chain: 'ONE',
  },
  {
    chainId: 322,
    name: 'Kucoin Chain',
    address: '', // of token
    symbol: 'KCS',
    logoUrl: 'https://govercity.com/assets/images/logos/kcs.svg', // of token
    networkName: 'Kucoin Chain',
    currency: 'KCS',
    decimals: 18,
    explorerName: '',
    explorerUrl: 'https://scan-testnet.kcc.network/',
    explorerApi: '',
    networkRpc: 'https://rpc-testnet.kcc.network/',
    networkRpc2: '',
    type: 'TEST',
    networkDecimals: 18,
    chain: 'KCS',
  },
];

module.exports = chains
