const Global = require('../models/Global.js');
const Rates = require('../models/Rates.js');
const Trending = require('../models/Trending.js');
const Tokens = require('../models/Token.js');
//=================={ethers library}===============================================
const asyncHandler = require('express-async-handler');

//=====================================================================================

async function getAxiosApi(url) {
  try {
    const response = await axios.get(url);
    return response.data;
  } catch (error) {
    console.log(error);
  }
}

// const tokenObj = {
//   id: 'gala',
//   symbol: 'gala',
//   name: 'GALA',
//   image:
//     'https://assets.coingecko.com/coins/images/12493/large/GALA-COINGECKO.png?1600233435',
//   current_price: 0.01329208,
//   market_cap: 351972612,
//   market_cap_rank: 95,
//   fully_diluted_valuation: 664460258,
//   total_volume: 393231240,
//   high_24h: 0.013401,
//   low_24h: 0.0131671,
//   price_change_24h: -0.000063155391006724,
//   price_change_percentage_24h: -0.47289,
//   market_cap_change_24h: -3979571.212519884,
//   market_cap_change_percentage_24h: -1.11801,
//   circulating_supply: 26485602971.0567,
//   total_supply: 26485208123.3413,
//   max_supply: 50000000000,
//   ath: 0.824837,
//   ath_change_percentage: -98.38895,
//   ath_date: '2021-11-26T01:03:48.731Z',
//   atl: 0.00013475,
//   atl_change_percentage: 9761.64337,
//   atl_date: '2020-12-28T08:46:48.367Z',
//   roi: null,
//   last_updated: '2023-09-27T08:40:27.468Z',
// };

// const userData = {
//   id: token?.id,
//   symbol: token?.symbol,
//   name: token?.name,
//   image: token?.image, // update with cloudinary image before sending to backend
//   current_price: token?.current_price,
//   market_cap: token?.market_cap,
//   market_cap_rank: token?.market_cap_rank,
//   fully_diluted_valuation: token?.fully_diluted_valuation,
//   total_volume: token?.total_volume,
//   high_24h: token?.high_24h,
//   low_24h: token?.low_24h,
//   price_change_24h: token?.price_change_24h,
//   price_change_percentage_24h: token?.price_change_percentage_24h,
//   market_cap_change_24h: token?.market_cap_change_24h,
//   market_cap_change_percentage_24h: token?.market_cap_change_percentage_24h,
//   circulating_supply: token?.circulating_supply,
//   total_supply: token?.total_supply,
//   max_supply: token?.max_supply,
//   ath: token?.ath,
//   ath_change_percentage: token?.ath_change_percentage,
//   ath_date: token?.ath_date,
//   atl: token?.atl,
//   atl_change_percentage: token?.atl_change_percentage,
//   atl_date: token?.atl_date,
//   roi: token?.roi,
//   last_updated: token?.last_updated,
// };

const addToken = asyncHandler(async (req, res) => {
  let result = await Tokens.create({
    id: req.body?.id,
    symbol: req.body?.symbol,
    name: req.body?.name,
    image: req.body?.image, // update with cloudinary image before sending to backend
    current_price: req.body?.current_price,
    market_cap: req.body?.market_cap,
    market_cap_rank: req.body?.market_cap_rank,
    fully_diluted_valuation: req.body?.fully_diluted_valuation,
    total_volume: req.body?.total_volume,
    high_24h: req.body?.high_24h,
    low_24h: req.body?.low_24h,
    price_change_24h: req.body?.price_change_24h,
    price_change_percentage_24h: req.body?.price_change_percentage_24h,
    market_cap_change_24h: req.body?.market_cap_change_24h,
    market_cap_change_percentage_24h:
      req.body?.market_cap_change_percentage_24h,
    circulating_supply: req.body?.circulating_supply,
    total_supply: req.body?.total_supply,
    max_supply: req.body?.max_supply,
    ath: req.body?.ath,
    ath_change_percentage: req.body?.ath_change_percentage,
    ath_date: req.body?.ath_date,
    atl: req.body?.atl,
    atl_change_percentage: req.body?.atl_change_percentage,
    atl_date: req.body?.atl_date,
    roi: req.body?.roi,
    last_updated: req.body?.last_updated,
  });

  if (result) {
    res.status(200).json(result);
  }
});

allCoins = [
  {
    id: 'onetokenburn',
    symbol: 'one',
    name: 'onetokenburn',
    image:
      'https://assets.coingecko.com/coins/images/30171/large/one.png?1683535182',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 1000000,
    max_supply: 1000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'okeycoin',
    symbol: 'okey',
    name: 'OKEYCOIN',
    image:
      'https://assets.coingecko.com/coins/images/26821/large/OKEYCOIN_LOGO.png?1660280496',
    current_price: 0.00000992,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: 99151,
    total_volume: 168.39,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 9808719870,
    max_supply: 10000000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: '2023-09-27T11:57:12.161Z',
  },
  {
    id: 'bridged-kyber-network-crystal-ethereum',
    symbol: 'knc_e',
    name: 'Bridged Kyber Network Crystal (Ethereum)',
    image:
      'https://assets.coingecko.com/coins/images/31925/large/knc.png?1695694460',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'novawchi',
    symbol: 'vachi',
    name: 'NOVAWCHI',
    image:
      'https://assets.coingecko.com/coins/images/29761/large/novawchi-infinity-of-nevoverse-coinmarketcap-logo.png?1681178882',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 9666666,
    max_supply: 9666666,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'alienswap',
    symbol: 'alien',
    name: 'AlienSwap',
    image:
      'https://assets.coingecko.com/coins/images/28320/large/alien.png?1669371307',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'flux-usdt',
    symbol: 'fusdt',
    name: 'Flux USDT',
    image:
      'https://assets.coingecko.com/coins/images/29581/large/fUSDT-320.png?1679813769',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'nexus-asa',
    symbol: 'gp',
    name: 'Nexus ASA',
    image:
      'https://assets.coingecko.com/coins/images/26823/large/gp.png?1660285199',
    current_price: 0.00010604,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: 1060360,
    total_volume: 16113.14,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 10000000000,
    max_supply: 10000000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: '2023-09-27T12:11:12.069Z',
  },
  {
    id: 'nefty',
    symbol: 'nefty',
    name: 'NeftyBlocks',
    image:
      'https://assets.coingecko.com/coins/images/28697/large/NB_logo_%283%29_%281%29.png?1673414356',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 41005180,
    max_supply: 100000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'apass-coin',
    symbol: 'apc',
    name: 'APass Coin',
    image:
      'https://assets.coingecko.com/coins/images/28685/large/APC.png?1673340722',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'mudra-mdr',
    symbol: 'mdr',
    name: 'Mudra MDR',
    image:
      'https://assets.coingecko.com/coins/images/26145/large/MudraLogo200x200.png?1656039972',
    current_price: 0.11967,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: 119670281,
    total_volume: 40289,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 1000000000,
    max_supply: 1000000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: '2023-09-27T12:09:40.547Z',
  },
  {
    id: 'mudra-exchange',
    symbol: 'mudra',
    name: 'Mudra',
    image:
      'https://assets.coingecko.com/coins/images/29045/large/imgpsh_fullsize_anim_%282%29.png?1676195070',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 1500000000,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'flux-usdc',
    symbol: 'fusdc',
    name: 'Flux USDC',
    image:
      'https://assets.coingecko.com/coins/images/29051/large/fUSDC_200x200.png?1676335208',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'moondogs',
    symbol: 'woof',
    name: 'Moondogs',
    image:
      'https://assets.coingecko.com/coins/images/29467/large/woof.png?1679112159',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 5999999,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'flux-frax',
    symbol: 'ffrax',
    name: 'Flux FRAX',
    image:
      'https://assets.coingecko.com/coins/images/29580/large/fFRAX-320.png?1679813767',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'flux-dai',
    symbol: 'fdai',
    name: 'Flux DAI',
    image:
      'https://assets.coingecko.com/coins/images/29052/large/fDAI_200x200.png?1676335235',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'monetas-2',
    symbol: 'mntg',
    name: 'Monetas',
    image:
      'https://assets.coingecko.com/coins/images/29667/large/MNTG_ICON_%281%29.png?1680593763',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 40000000,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'fluid-tusd',
    symbol: 'ftusd',
    name: 'Fluid TUSD',
    image:
      'https://assets.coingecko.com/coins/images/28474/large/fTUSD-200x200.png?1671002558',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'minu',
    symbol: 'minu',
    name: 'Minu',
    image:
      'https://assets.coingecko.com/coins/images/29151/large/Minu_Logo.jpg?1676972329',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 100000000000000,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'ai-supreme',
    symbol: 'aisp',
    name: 'AI Supreme',
    image:
      'https://assets.coingecko.com/coins/images/30900/large/200.png?1688549201',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 21000000,
    max_supply: 21000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'union-finance',
    symbol: 'union',
    name: 'Union Finance',
    image:
      'https://assets.coingecko.com/coins/images/30556/large/Mark.png?1685013645',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 1000000000,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'minterest',
    symbol: 'mnt',
    name: 'Minterest',
    image:
      'https://assets.coingecko.com/coins/images/29455/large/Minterest.png?1678963801',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 3156714,
    max_supply: 65902270,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'mintera',
    symbol: 'mnte',
    name: 'Mintera',
    image:
      'https://assets.coingecko.com/coins/images/28774/large/Mintera_Logo_CoinGecko.png?1674480509',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 65000000,
    max_supply: 65000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'minnapad',
    symbol: 'minna',
    name: 'Minnapad',
    image:
      'https://assets.coingecko.com/coins/images/31949/large/Minnapad-Logo_M_200x200.png?1695726378',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 1000000000,
    max_supply: 1000000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'metaverse-kombat',
    symbol: 'mvk',
    name: 'Metaverse Kombat',
    image:
      'https://assets.coingecko.com/coins/images/30180/large/Untitled_design_%282%29.png?1683598415',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 300000000,
    max_supply: 300000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'meta-launcher',
    symbol: 'mtla',
    name: 'Meta Launcher',
    image:
      'https://assets.coingecko.com/coins/images/29331/large/logo_circle.png?1678172488',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 500000000,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'fluid-dai',
    symbol: 'fdai',
    name: 'Fluid DAI',
    image:
      'https://assets.coingecko.com/coins/images/28473/large/fDAI-200x200.png?1671002526',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'fluid',
    symbol: 'fld',
    name: 'FluidAI',
    image:
      'https://assets.coingecko.com/coins/images/25579/large/fluid.jpeg?1691655408',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'metajuice',
    symbol: 'vcoin',
    name: 'Metajuice',
    image:
      'https://assets.coingecko.com/coins/images/28577/large/vcoin.png?1671879909',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'aboat-token-2',
    symbol: 'aboat',
    name: 'Aboat Token',
    image:
      'https://assets.coingecko.com/coins/images/30132/large/aboat.jpg?1683270108',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 1000000000000,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'mausdt',
    symbol: 'mausdt',
    name: 'Morpho-Aave Tether USD',
    image:
      'https://assets.coingecko.com/coins/images/29834/large/maUSDT_%284%29.png?1681718428',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'bridged-kyber-network-crystal-bsc',
    symbol: 'knc_b',
    name: 'Bridged Kyber Network Crystal (BSC)',
    image:
      'https://assets.coingecko.com/coins/images/31927/large/knc.png?1695695331',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'wusd',
    symbol: 'wusd',
    name: 'Wrapped USD',
    image:
      'https://assets.coingecko.com/coins/images/28854/large/wusd.png?1675567058',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 83532.5701477539,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'mausdc',
    symbol: 'mausdc',
    name: 'Morpho-Aave USD Coin',
    image:
      'https://assets.coingecko.com/coins/images/29835/large/maUSDC.jpg?1681718450',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'floyx-new',
    symbol: 'floyx',
    name: 'Floyx',
    image:
      'https://assets.coingecko.com/coins/images/29527/large/FloyxLogo_200x200.png?1679476684',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 0,
    max_supply: 45000000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'finx',
    symbol: 'finx',
    name: 'FINX',
    image:
      'https://assets.coingecko.com/coins/images/30263/large/FINX_logo.png?1684138378',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'unlock-maverick',
    symbol: 'unkmav',
    name: 'Unlock Maverick',
    image:
      'https://assets.coingecko.com/coins/images/31264/large/clean.jpg?1692067517',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: 0,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: '2023-09-27T12:10:57.014Z',
  },
  {
    id: 'astrava',
    symbol: 'ast',
    name: 'Astrava',
    image:
      'https://assets.coingecko.com/coins/images/31122/large/Astrava2.jpeg?1690773767',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 100000000,
    max_supply: 100000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'matic-plenty-bridge',
    symbol: 'matic.e',
    name: 'MATIC (Plenty Bridge)',
    image:
      'https://assets.coingecko.com/coins/images/29105/large/9b1e977d00b5d887608b156705a10759.png?1676620316',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'coinlocally',
    symbol: 'clyc',
    name: 'Coinlocally',
    image:
      'https://assets.coingecko.com/coins/images/28808/large/light.png?1674304252',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 1000000000,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'algomint',
    symbol: 'gomint',
    name: 'Algomint',
    image:
      'https://assets.coingecko.com/coins/images/25884/large/gomint.png?1654414812',
    current_price: 0.00532154,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: 5321542,
    total_volume: 46.72,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 1000000000,
    max_supply: 1000000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: '2023-09-27T12:11:11.456Z',
  },
  {
    id: 'lvusd',
    symbol: 'lvusd',
    name: 'lvUSD',
    image:
      'https://assets.coingecko.com/coins/images/28971/large/lvusd.png?1675748391',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'fina',
    symbol: 'fina',
    name: 'Fina',
    image:
      'https://assets.coingecko.com/coins/images/30626/large/fina.png?1685777561',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 115000000,
    max_supply: 1000000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'fastswap-bsc-2',
    symbol: 'fast',
    name: 'Fastswap (BSC)',
    image:
      'https://assets.coingecko.com/coins/images/30134/large/FAST.jpg?1683271931',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 1000000000,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'luxo',
    symbol: 'luxo',
    name: 'Luxo',
    image:
      'https://assets.coingecko.com/coins/images/25545/large/ik7UTHJR_400x400.jpg?1652327828',
    current_price: 0.0459,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: 45900000,
    total_volume: 199.94,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 1000000000,
    max_supply: 1000000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: '2023-09-27T12:10:33.933Z',
  },
  {
    id: 'coinbet-finance',
    symbol: 'cfi',
    name: 'Coinbet Finance',
    image:
      'https://assets.coingecko.com/coins/images/28809/large/coinbet-transparent.png?1674304459',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 100000000,
    max_supply: 100000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'cloudbase',
    symbol: 'cloud',
    name: 'CloudBase',
    image:
      'https://assets.coingecko.com/coins/images/31391/large/CloudBaselogo_%281%29.png?1692762173',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 93500000,
    max_supply: 100000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'clashmon-ignition-torch',
    symbol: 'torch',
    name: 'Torch',
    image:
      'https://assets.coingecko.com/coins/images/31788/large/Coin_TORCH_FullColor_circle_200.png?1695019082',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 1000000000,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'astra-nova',
    symbol: '$rvv',
    name: 'Astra Nova',
    image:
      'https://assets.coingecko.com/coins/images/28578/large/rvv.png?1671883407',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'bridged-curve-dao-token-stargate',
    symbol: 'crv',
    name: 'Bridged Curve DAO Token (Stargate)',
    image:
      'https://assets.coingecko.com/coins/images/31182/large/CurveFi_32.png?1691122756',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'lopo',
    symbol: 'lopo',
    name: 'LOPO',
    image:
      'https://assets.coingecko.com/coins/images/29250/large/IMG_20230220_222454_192.png?1677642606',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 100000000,
    max_supply: 100000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'leetswap-canto',
    symbol: 'leet',
    name: 'LeetSwap (Canto)',
    image:
      'https://assets.coingecko.com/coins/images/31129/large/leet.png?1690856091',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'veax',
    symbol: 'veax',
    name: 'Veax',
    image:
      'https://assets.coingecko.com/coins/images/28387/large/veax.png?1670065279',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: null,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'lee',
    symbol: 'lee',
    name: 'Lee',
    image:
      'https://assets.coingecko.com/coins/images/29981/large/LeeToken.png?1682407438',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 0,
    max_supply: 3500000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'bracelet',
    symbol: 'brc',
    name: 'Bracelet',
    image:
      'https://assets.coingecko.com/coins/images/28866/large/bracelet-token.png?1674996027',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 1000000000,
    max_supply: null,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
  {
    id: 'ledgerland',
    symbol: 'lger',
    name: 'LedgerLand',
    image:
      'https://assets.coingecko.com/coins/images/30956/large/LEGR_logo.png?1689217120',
    current_price: null,
    market_cap: null,
    market_cap_rank: null,
    fully_diluted_valuation: null,
    total_volume: null,
    high_24h: null,
    low_24h: null,
    price_change_24h: null,
    price_change_percentage_24h: null,
    market_cap_change_24h: null,
    market_cap_change_percentage_24h: null,
    circulating_supply: null,
    total_supply: 21000000,
    max_supply: 21000000,
    ath: null,
    ath_change_percentage: 0,
    ath_date: null,
    atl: null,
    atl_change_percentage: 0,
    atl_date: null,
    roi: null,
    last_updated: null,
  },
];

module.exports = {
  addToken,
};
